"""
Unit tests for lj.apply_symmetries.

The symmetry list format is:
    [[resname, equivalent_atom_1, equivalent_atom_2, ...], ...]

sb_type format is: atomname_molname_resnum  (e.g. "NH1_ARG_5")

apply_symmetries returns a DataFrame of *new* rows generated by replacing
atom names according to the symmetry rules. It does NOT include the original
rows — those are concatenated by the caller in generate_LJ.
"""

import sys
import types
import pandas as pd
import pytest


@pytest.fixture(scope="module")
def apply_symmetries():
    """Load apply_symmetries with minimal stubs."""

    # --- Stub mg ---
    stub_mg = types.ModuleType("multiego.mg")
    stub_mg.generate_MG_LJ = lambda *args, **kwargs: None
    sys.modules["multiego.mg"] = stub_mg

    # --- Stub bonded ---
    stub_bonded = types.ModuleType("multiego.bonded")
    stub_bonded.generate_bond_distance_data = lambda *args, **kwargs: None
    sys.modules["multiego.bonded"] = stub_bonded

    # --- Stub model_config ---
    stub_mc = types.ModuleType("multiego.model_config")
    stub_mc.config = types.SimpleNamespace(max_bond_separation=5, bond14_separation=3)
    sys.modules["multiego.model_config"] = stub_mc

    # --- Other modules (no attributes needed) ---
    sys.modules.setdefault("multiego.type_definitions", types.ModuleType("multiego.type_definitions"))
    sys.modules.setdefault("multiego.io", types.ModuleType("multiego.io"))

    from multiego.lj import apply_symmetries

    return apply_symmetries


def _make_ensemble(sbtype_resname_map, molecule_name="MOL1"):
    """
    Build a minimal mock ensemble whose topology_dataframe contains the
    columns needed by apply_symmetries: sb_type, resname, molecule_name,
    and resnum (parsed from the last '_'-delimited segment of sb_type).

    sb_type format: atomname_molname_resnum  (e.g. "NH1_ARG_5" → resnum 5)
    """
    rows = []
    for sb_type, resname in sbtype_resname_map.items():
        resnum = int(sb_type.rsplit("_", 1)[-1])
        rows.append(
            {
                "sb_type": sb_type,
                "resname": resname,
                "molecule_name": molecule_name,
                "resnum": resnum,
            }
        )
    topology_dataframe = pd.DataFrame(rows)
    ensemble = types.SimpleNamespace(topology_dataframe=topology_dataframe)
    return ensemble


def _make_contacts(rows):
    """
    Build a contacts DataFrame from a list of (ai, aj) tuples.
    Extra columns are filled with neutral defaults so set_sig_epsilon-like
    operations would not fail if called, but apply_symmetries only touches ai/aj.
    """
    return pd.DataFrame(
        [
            {"ai": ai, "aj": aj, "epsilon": 0.1, "sigma": 0.35, "probability": 0.9, "rc_probability": 0.01}
            for ai, aj in rows
        ]
    )


# ---------------------------------------------------------------------------
# Basic two-atom symmetry (e.g. ASP OD1 / OD2)
# ---------------------------------------------------------------------------


class TestTwoAtomSymmetry:

    def _asp_ensemble(self):
        return _make_ensemble(
            {
                "OD1_ASP_3": "ASP",
                "OD2_ASP_3": "ASP",
                "CA_ALA_1": "ALA",
            }
        )

    def test_symmetric_contact_generates_swapped_row(self, apply_symmetries):
        """A contact involving OD1 of ASP should produce a mirrored row with OD2."""
        ensemble = self._asp_ensemble()
        contacts = _make_contacts([("OD1_ASP_3", "CA_ALA_1")])
        symmetry = [["ASP", "OD1", "OD2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        ai_values = set(result["ai"])
        aj_values = set(result["aj"])
        # OD1 should have been renamed to OD2 in at least one row
        assert "OD2_ASP_3" in ai_values or "OD2_ASP_3" in aj_values

    def test_non_matching_residue_not_affected(self, apply_symmetries):
        """Contacts that don't involve the symmetric residue should not appear."""
        ensemble = self._asp_ensemble()
        contacts = _make_contacts([("CA_ALA_1", "CA_ALA_1")])
        symmetry = [["ASP", "OD1", "OD2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)
        assert result.empty

    def test_both_permutations_generated(self, apply_symmetries):
        """
        For two equivalent atoms A and B, both A→B and B→A permutations
        should appear so the symmetry is truly bidirectional.
        """
        ensemble = self._asp_ensemble()
        # Contact uses OD1; symmetry should also generate a version with OD2
        contacts = _make_contacts([("OD1_ASP_3", "CA_ALA_1")])
        symmetry = [["ASP", "OD1", "OD2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        ais = set(result["ai"])
        ajs = set(result["aj"])
        assert "OD2_ASP_3" in ais or "OD2_ASP_3" in ajs

    def test_no_duplicates_in_result(self, apply_symmetries):
        """apply_symmetries should deduplicate its output."""
        ensemble = self._asp_ensemble()
        # Same contact twice to provoke potential duplicates
        contacts = _make_contacts(
            [
                ("OD1_ASP_3", "CA_ALA_1"),
                ("OD1_ASP_3", "CA_ALA_1"),
            ]
        )
        symmetry = [["ASP", "OD1", "OD2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)
        assert len(result) == len(result.drop_duplicates())


# ---------------------------------------------------------------------------
# Three-atom symmetry (e.g. ARG NH1 / NH2 — two equivalent guanidinium nitrogens)
# ---------------------------------------------------------------------------


class TestThreeAtomSymmetry:

    def _arg_ensemble(self):
        return _make_ensemble(
            {
                "NH1_ARG_5": "ARG",
                "NH2_ARG_5": "ARG",
                "OD1_ASP_3": "ASP",
            }
        )

    def test_two_equivalent_atoms_both_appear(self, apply_symmetries):
        """
        A contact with NH1 of ARG should generate a version with NH2
        and vice versa, covering both permutations.
        """
        ensemble = self._arg_ensemble()
        contacts = _make_contacts([("NH1_ARG_5", "OD1_ASP_3")])
        symmetry = [["ARG", "NH1", "NH2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "NH2_ARG_5" in all_atoms

    def test_symmetric_atom_in_aj_also_renamed(self, apply_symmetries):
        """Symmetry should apply when the symmetric atom appears in aj, not just ai."""
        ensemble = self._arg_ensemble()
        contacts = _make_contacts([("OD1_ASP_3", "NH1_ARG_5")])
        symmetry = [["ARG", "NH1", "NH2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "NH2_ARG_5" in all_atoms


# ---------------------------------------------------------------------------
# Multiple independent symmetry rules
# ---------------------------------------------------------------------------


class TestMultipleSymmetryRules:

    def _ensemble(self):
        return _make_ensemble(
            {
                "OD1_ASP_3": "ASP",
                "OD2_ASP_3": "ASP",
                "NH1_ARG_5": "ARG",
                "NH2_ARG_5": "ARG",
                "CA_GLY_1": "GLY",
            }
        )

    def test_two_rules_each_generate_rows(self, apply_symmetries):
        """When two symmetry rules are given, both should produce output rows."""
        ensemble = self._ensemble()
        contacts = _make_contacts(
            [
                ("OD1_ASP_3", "CA_GLY_1"),
                ("NH1_ARG_5", "CA_GLY_1"),
            ]
        )
        symmetry = [
            ["ASP", "OD1", "OD2"],
            ["ARG", "NH1", "NH2"],
        ]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "OD2_ASP_3" in all_atoms
        assert "NH2_ARG_5" in all_atoms

    def test_rules_do_not_cross_contaminate(self, apply_symmetries):
        """The ASP rule should not rename ARG atoms and vice versa."""
        ensemble = self._ensemble()
        contacts = _make_contacts([("OD1_ASP_3", "CA_GLY_1")])
        symmetry = [
            ["ASP", "OD1", "OD2"],
            ["ARG", "NH1", "NH2"],
        ]

        result = apply_symmetries(ensemble, contacts, symmetry)

        # ARG atoms should not appear — only ASP symmetry applies here
        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "NH1_ARG_5" not in all_atoms
        assert "NH2_ARG_5" not in all_atoms


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:

    def test_empty_symmetry_list_returns_empty(self, apply_symmetries):
        """An empty symmetry list should return an empty DataFrame."""
        ensemble = _make_ensemble({"OD1_ASP_3": "ASP"})
        contacts = _make_contacts([("OD1_ASP_3", "OD1_ASP_3")])

        result = apply_symmetries(ensemble, contacts, [])
        assert result.empty

    def test_empty_contacts_returns_empty(self, apply_symmetries):
        """An empty contacts DataFrame should return an empty result."""
        ensemble = _make_ensemble({"OD1_ASP_3": "ASP", "OD2_ASP_3": "ASP"})
        contacts = _make_contacts([])

        result = apply_symmetries(ensemble, contacts, [["ASP", "OD1", "OD2"]])
        assert result.empty

    def test_none_entry_in_symmetry_list_skipped(self, apply_symmetries):
        """A None or empty entry in the symmetry list should be silently skipped."""
        ensemble = _make_ensemble({"OD1_ASP_3": "ASP", "OD2_ASP_3": "ASP", "CA_GLY_1": "GLY"})
        contacts = _make_contacts([("OD1_ASP_3", "CA_GLY_1")])

        # None/[] entries should not cause errors
        result = apply_symmetries(ensemble, contacts, [None, [], ["ASP", "OD1", "OD2"]])
        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "OD2_ASP_3" in all_atoms

    def test_original_rows_are_preserved_and_augmented(self, apply_symmetries):
        """
        apply_symmetries returns the original rows PLUS the symmetry-generated ones.
        """
        ensemble = _make_ensemble({"OD1_ASP_3": "ASP", "OD2_ASP_3": "ASP", "CA_GLY_1": "GLY"})
        contacts = _make_contacts([("OD1_ASP_3", "CA_GLY_1")])
        symmetry = [["ASP", "OD1", "OD2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        # ✅ original row must be present
        original_present = ((result["ai"] == "OD1_ASP_3") & (result["aj"] == "CA_GLY_1")).any()
        assert original_present

        # ✅ symmetrized row must also be present
        sym_present = ((result["ai"] == "OD2_ASP_3") & (result["aj"] == "CA_GLY_1")).any()
        assert sym_present

        # ✅ result must be strictly larger than input
        assert len(result) > len(contacts)

    def test_result_columns_match_input(self, apply_symmetries):
        """Output columns should be identical to the input columns."""
        ensemble = _make_ensemble({"OD1_ASP_3": "ASP", "OD2_ASP_3": "ASP", "CA_GLY_1": "GLY"})
        contacts = _make_contacts([("OD1_ASP_3", "CA_GLY_1")])
        symmetry = [["ASP", "OD1", "OD2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)
        assert set(result.columns) == set(contacts.columns)


# ---------------------------------------------------------------------------
# CTER / NTER terminal-residue keywords
# ---------------------------------------------------------------------------


class TestTerminalKeywords:
    """
    CTER resolves to atoms whose resnum equals the maximum resnum per molecule.
    NTER resolves to atoms whose resnum equals the minimum resnum per molecule.
    """

    def _cter_ensemble(self):
        # 3-residue chain: resnum 1 (N-term), 2 (middle), 3 (C-term)
        return _make_ensemble(
            {
                "N_ALA_1": "ALA",  # NTER
                "O1_ALA_1": "ALA",  # NTER
                "O2_ALA_1": "ALA",  # NTER
                "CA_GLY_2": "GLY",  # middle
                "N_ALA_3": "ALA",  # CTER
                "O1_ALA_3": "ALA",  # CTER
                "O2_ALA_3": "ALA",  # CTER
            }
        )

    def test_cter_applies_to_last_residue(self, apply_symmetries):
        """CTER O1 O2 should rename O1→O2 (and vice versa) only for the C-terminal residue."""
        ensemble = self._cter_ensemble()
        contacts = _make_contacts([("O1_ALA_3", "CA_GLY_2")])
        symmetry = [["CTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        # C-terminal O2 should appear
        assert "O2_ALA_3" in all_atoms

    def test_cter_does_not_affect_middle_residues(self, apply_symmetries):
        """CTER should not rename atoms in non-terminal residues."""
        ensemble = self._cter_ensemble()
        # Contact involves only the middle residue — CTER should not touch it
        contacts = _make_contacts([("CA_GLY_2", "CA_GLY_2")])
        symmetry = [["CTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)
        assert result.empty

    def test_cter_does_not_affect_nter_residue(self, apply_symmetries):
        """CTER should not rename atoms belonging to the N-terminal residue."""
        ensemble = self._cter_ensemble()
        contacts = _make_contacts([("O1_ALA_1", "CA_GLY_2")])
        symmetry = [["CTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)
        # No CTER atoms involved → result should be empty
        assert result.empty

    def test_nter_applies_to_first_residue(self, apply_symmetries):
        """NTER O1 O2 should rename O1→O2 (and vice versa) only for the N-terminal residue."""
        ensemble = self._cter_ensemble()
        contacts = _make_contacts([("O1_ALA_1", "CA_GLY_2")])
        symmetry = [["NTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "O2_ALA_1" in all_atoms

    def test_nter_does_not_affect_cter_residue(self, apply_symmetries):
        """NTER should not rename atoms belonging to the C-terminal residue."""
        ensemble = self._cter_ensemble()
        contacts = _make_contacts([("O1_ALA_3", "CA_GLY_2")])
        symmetry = [["NTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)
        assert result.empty

    def test_cter_and_nter_together(self, apply_symmetries):
        """Both CTER and NTER rules can be active simultaneously without interference."""
        ensemble = self._cter_ensemble()
        contacts = _make_contacts(
            [
                ("O1_ALA_1", "CA_GLY_2"),  # NTER contact
                ("O1_ALA_3", "CA_GLY_2"),  # CTER contact
            ]
        )
        symmetry = [["NTER", "O1", "O2"], ["CTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        assert "O2_ALA_1" in all_atoms  # NTER swap present
        assert "O2_ALA_3" in all_atoms  # CTER swap present

    def test_cter_multi_molecule(self, apply_symmetries):
        """Each molecule gets its own CTER independently."""
        # Two separate molecules (different molecule_name) — build manually
        import pandas as pd

        topo = pd.DataFrame(
            [
                {"sb_type": "O1_ALA_2", "resname": "ALA", "molecule_name": "MOLA", "resnum": 2},
                {"sb_type": "O2_ALA_2", "resname": "ALA", "molecule_name": "MOLA", "resnum": 2},
                {"sb_type": "N_ALA_1", "resname": "ALA", "molecule_name": "MOLA", "resnum": 1},
                {"sb_type": "O1_GLY_3", "resname": "GLY", "molecule_name": "MOLB", "resnum": 3},
                {"sb_type": "O2_GLY_3", "resname": "GLY", "molecule_name": "MOLB", "resnum": 3},
                {"sb_type": "N_GLY_1", "resname": "GLY", "molecule_name": "MOLB", "resnum": 1},
            ]
        )
        ensemble = types.SimpleNamespace(topology_dataframe=topo)

        # Contact between C-terminals of both molecules
        contacts = _make_contacts(
            [
                ("O1_ALA_2", "N_GLY_1"),  # CTER of MOLA with non-CTER of MOLB
                ("O1_GLY_3", "N_ALA_1"),  # CTER of MOLB with non-CTER of MOLA
            ]
        )
        symmetry = [["CTER", "O1", "O2"]]

        result = apply_symmetries(ensemble, contacts, symmetry)

        all_atoms = set(result["ai"]) | set(result["aj"])
        # C-terminal of MOLA (resnum 2) should be swapped
        assert "O2_ALA_2" in all_atoms
        # C-terminal of MOLB (resnum 3) should be swapped
        assert "O2_GLY_3" in all_atoms
