import { Link } from "react-router-dom";

const COLAB_URL =
  "https://colab.research.google.com/github/multi-ego/multi-eGO/blob/main/tools/colab/run_mg_openmm.ipynb";

const STEPS = [
  {
    number: "01",
    title: "Install dependencies",
    description:
      "OpenMM, ParmEd, and MDTraj are installed automatically in the first cell. No local setup required.",
  },
  {
    number: "02",
    title: "Upload input files",
    description:
      "Upload topol_mego.top, ffnonbonded.itp, and system.gro — the three files produced by the mg force-field generation and initial GROMACS setup steps.",
  },
  {
    number: "03",
    title: "Energy minimisation",
    description:
      "Steepest-descents minimisation removes any bad contacts in the starting structure before dynamics begin.",
  },
  {
    number: "04",
    title: "NVT production run",
    description:
      "Langevin dynamics at 300 K, 5 fs timestep, 2.5 nm LJ cutoff — matching the ff_aa.mdp protocol. GPU-accelerated when a CUDA device is available in Colab.",
  },
  {
    number: "05",
    title: "Energy analysis",
    description:
      "Potential energy and temperature are plotted automatically so you can check that the simulation is well-equilibrated.",
  },
  {
    number: "06",
    title: "Download trajectory",
    description:
      "The trajectory is converted from DCD to XTC (GROMACS format) with MDTraj, ready to be analysed with cmdata.",
  },
];

const PREREQS = [
  {
    file: "topol_mego.top",
    from: "mego --system … --egos mg",
    note: "GROMACS topology with multi-eGO mg force field",
  },
  {
    file: "ffnonbonded.itp",
    from: "mego --system … --egos mg",
    note: "Non-bonded LJ parameters, referenced by the topology",
  },
  {
    file: "system.gro",
    from: "gmx pdb2gmx + gmx grompp/mdrun (energy minimisation)",
    note: "Starting coordinates in GROMACS format",
  },
];

export default function Simulation() {
  return (
    <div className="mx-auto max-w-6xl space-y-16 px-6 py-12">
      {/* Header */}
      <div className="space-y-4">
        <h1 className="section-heading">mg Reference Simulation</h1>
        <p className="max-w-2xl text-gray-400">
          Run the molten-globule reference simulation directly in your browser — no local GPU or
          GROMACS installation required. The notebook runs on Google Colab using{" "}
          <a
            href="https://openmm.org"
            target="_blank"
            rel="noopener noreferrer"
            className="text-brand-400 hover:underline"
          >
            OpenMM
          </a>{" "}
          and is free to use with a Google account.
        </p>
      </div>

      {/* Colab CTA */}
      <div className="rounded-xl border border-brand-800 bg-brand-950/30 p-8 text-center">
        <p className="mb-2 text-sm font-medium uppercase tracking-widest text-brand-400">
          Run in your browser
        </p>
        <h2 className="mb-6 text-2xl font-bold text-white">
          Multi-<em>e</em>GO mg simulation · OpenMM notebook
        </h2>
        <a
          href={COLAB_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-3 rounded-lg bg-[#F9AB00] px-6 py-3 text-sm font-semibold text-gray-900 transition hover:bg-[#F9AB00]/90"
        >
          <img
            src="https://colab.research.google.com/assets/colab-badge.svg"
            alt="Open in Colab"
            className="h-5"
          />
          Open in Google Colab
        </a>
        <p className="mt-4 text-xs text-gray-500">
          Free GPU available · requires a Google account · no installation needed
        </p>
      </div>

      {/* Prerequisites */}
      <div>
        <h2 className="section-heading mb-6">Prerequisites</h2>
        <p className="mb-4 text-gray-400">
          Before opening the notebook, complete steps 1–3 of the workflow to generate the mg force
          field and initial coordinates.
        </p>
        <div className="overflow-x-auto rounded-xl border border-gray-800">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-800 bg-gray-900/60">
                <th className="px-4 py-3 text-left font-medium text-gray-400">File</th>
                <th className="px-4 py-3 text-left font-medium text-gray-400">Generated by</th>
                <th className="px-4 py-3 text-left font-medium text-gray-400">Description</th>
              </tr>
            </thead>
            <tbody>
              {PREREQS.map((p) => (
                <tr key={p.file} className="border-b border-gray-800/50 last:border-0">
                  <td className="px-4 py-3">
                    <code className="rounded bg-gray-800 px-1.5 py-0.5 text-xs text-brand-300">
                      {p.file}
                    </code>
                  </td>
                  <td className="px-4 py-3 font-mono text-xs text-gray-300">{p.from}</td>
                  <td className="px-4 py-3 text-gray-400">{p.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-4 flex gap-3">
          <Link to="/setup" className="btn-secondary text-sm">
            Setup assistant →
          </Link>
          <Link to="/config" className="btn-secondary text-sm">
            Config builder →
          </Link>
        </div>
      </div>

      {/* What the notebook does */}
      <div>
        <h2 className="section-heading mb-6">What the notebook does</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {STEPS.map((step) => (
            <div key={step.number} className="card">
              <span className="mb-3 block font-mono text-3xl font-bold text-brand-800">
                {step.number}
              </span>
              <h3 className="mb-2 font-semibold text-white">{step.title}</h3>
              <p className="text-sm text-gray-400">{step.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Output & next steps */}
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="card">
          <h3 className="mb-3 font-semibold text-white">Output files</h3>
          <ul className="space-y-2 text-sm text-gray-400">
            {[
              ["trajectory.xtc", "Full trajectory in GROMACS XTC format"],
              ["simulation.log", "Per-frame energy, temperature, and timing"],
              ["energy_plot.png", "Potential energy and temperature plots"],
              ["final.pdb", "Final frame coordinates"],
              ["checkpoint.xml", "OpenMM checkpoint for restarting"],
            ].map(([f, desc]) => (
              <li key={f} className="flex gap-3">
                <code className="shrink-0 rounded bg-gray-800 px-1.5 py-0.5 text-xs text-brand-300">
                  {f}
                </code>
                <span>{desc}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="card">
          <h3 className="mb-3 font-semibold text-white">Next steps</h3>
          <ol className="space-y-3 text-sm text-gray-400">
            <li className="flex gap-3">
              <span className="font-mono text-brand-400">1.</span>
              <span>
                Extract contact histograms from the trajectory with{" "}
                <code className="rounded bg-gray-800 px-1 text-xs text-brand-300">cmdata</code>
                {" "}(requires a GROMACS{" "}
                <code className="rounded bg-gray-800 px-1 text-xs text-brand-300">.tpr</code>{" "}
                run-input file).
              </span>
            </li>
            <li className="flex gap-3">
              <span className="font-mono text-brand-400">2.</span>
              <span>
                Convert histograms to contact matrices with{" "}
                <code className="rounded bg-gray-800 px-1 text-xs text-brand-300">make_mat.py</code>.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="font-mono text-brand-400">3.</span>
              <span>
                Generate the production force field with{" "}
                <code className="rounded bg-gray-800 px-1 text-xs text-brand-300">
                  mego --config config.yml
                </code>
                .
              </span>
            </li>
          </ol>
        </div>
      </div>

      {/* Note on compatibility */}
      <div className="rounded-xl border border-yellow-900/50 bg-yellow-950/20 p-5 text-sm text-yellow-200/80">
        <strong className="text-yellow-300">Experimental:</strong> The multi-eGO OpenMM interface
        is under active development. The mg force field uses C6/C12 non-bonded parameters with a
        geometric combination rule and no electrostatics — parameters that most OpenMM GROMACS
        readers handle correctly, but edge cases may arise with unusual topologies. If you encounter
        loading errors, please{" "}
        <a
          href="https://github.com/multi-ego/multi-eGO/issues"
          target="_blank"
          rel="noopener noreferrer"
          className="text-yellow-300 underline hover:text-yellow-200"
        >
          open an issue
        </a>
        .
      </div>
    </div>
  );
}
