name: cmdata 

on:
  push:
    paths:
      - 'tools/cmdata/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'tools/cmdata/**'
      - 'tests/**'

permissions:
  contents: read
  actions: write

jobs:
  build-linux-gromacs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Get GROMACS commit hash
      id: gmx-hash
      run: |
        echo "hash=$(git ls-remote https://github.com/multi-ego/gromacs.git refs/heads/release-2025 | cut -f1)" >> $GITHUB_OUTPUT

    - name: Cache GROMACS installation
      id: cache-gromacs
      uses: actions/cache@v5
      with:
        path: /usr/local/gromacs
        key: gromacs-release-2025-${{ steps.gmx-hash.outputs.hash }}

    - name: Build GROMACS
      if: steps.cache-gromacs.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 -b release-2025 https://github.com/multi-ego/gromacs.git
        cd gromacs; mkdir build; cd build
        cmake .. -DGMX_FFT_LIBRARY=fftpack -DBUILD_TESTING=OFF -DGMX_INSTALL_LEGACY_API=ON -DGMX_IMD=OFF
        make -j2
        sudo make install
    - name: Build cmdata 
      run: |
        cd tools/cmdata; mkdir build; cd build
        cmake ../ -DCMDATA_BUILD_TESTS=ON
        make
        sudo make install
    - name: Test cmdata
      run: |
        cd tools/cmdata/build
        make test
        cmdata --help
    - name: Run cmdata regtests
      run: |
        source /usr/local/gromacs/bin/GMXRC
        cd tests; bash run_cmdata.sh; cd ..
        

