name: cmdata 

on:
  push:
    paths:
      - 'tools/cmdata/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'tools/cmdata/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  build-linux-gromacs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Install generic packages
      run: |
        sudo apt-get update -qq
    - name: Build gromacs 
      run: |
        git clone --depth 1 -b release-2025 https://github.com/multi-ego/gromacs.git
        cd gromacs; mkdir build; cd build
        cmake .. -DGMX_FFT_LIBRARY=fftpack -DBUILD_TESTING=OFF -DGMX_INSTALL_LEGACY_API=ON -DGMX_IMD=OFF
        make -j2 
        sudo make install
    - name: Build cmdata 
      run: |
        cd tools/cmdata; mkdir build; cd build
        cmake ../ -DCMDATA_BUILD_TESTS=ON
        make
        sudo make install
    - name: Test cmdata
      run: |
        cd tools/cmdata/build
        make test
        cmdata --help
    - name: Run cmdata regtests
      run: |
        source /usr/local/gromacs/bin/GMXRC
        cd tests; bash run_cmdata.sh; cd ..
        

